name: 02 - workflow - event

on: 
  push:
  Pull_request:
  shedule:
    - cron: "*/5 * * * *"  

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger name
              run: echo "I've been triggered by a(n) ${{ github.event_name }} event." 