name: 02 - workflow - event

on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger name
              run: echo "I've have been triggered a(n) ${{ github.event_name }} event." 
